# Generated by Django 6.0.8 on 2026-08-08 14:26

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('book', 'Book'), ('game', 'Video Game'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('music', 'Music')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('planning', 'Planning'), ('ongoing', 'Ongoing'), ('dropped', 'Dropped')], default='planning', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
