# Generated by Django 6.0.8 on 2026-08-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('book', 'Book'), ('game', 'Video Game'), ('music', 'Music'), ('comics', 'Comics'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('planned', 'Planned'), ('paused', 'Paused'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('dropped', 'Dropped'), ('rewatching', 'Rewatching')], default='planned', max_length=20),
        ),
    ]
