# Generated by Django 6.0.8 on 2026-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_mediaitem_media_type_alter_mediaitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='external_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='external_source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
