# Generated by Django 6.0.8 on 2026-08-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_mediaitem_cover_image_url_mediaitem_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('book', 'Book'), ('game', 'Video Game'), ('anime', 'Anime'), ('music', 'Music'), ('comics', 'Comics'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua')], max_length=20),
        ),
    ]
